networks:
  cs5200-network:
    driver: bridge

services:
  php-pbp:
    image: php:8.2-apache
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-dev
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html
    depends_on:
      - mysql
    networks:
      - cs5200-network

  mysql:
    image: mysql:latest
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 5200
      MYSQL_DATABASE: Practicum1
      MYSQL_USER: student
      MYSQL_PASSWORD: student
    ports:
      - "3306:3306"
    networks:
      - cs5200-network
    volumes:
      - ./local/mysql:/var/lib/mysql
      - ./mysql_scripts/:/var/lib/mysql-files/
  
  phpadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin-container
    depends_on:
      - mysql
    networks:
      - cs5200-network
    ports:
      - "8081:80"
    links:
      - mysql:db
    volumes:
      - ./local/phpadmin:/sessions
    
